## E19004_Akshay_Chauhan
### AIM: I have picked 20 Wikipedia articles on 5 soccer players, 5 basketball players, 5 famous Indian statisticians and 5 famous Indian scientists. Then I have used euclidean distance with and without normalization and cosine similarity to find the similarity between all 20 articles. I have then implemented a 3NN search algorithm to club similar articles together and have noted my inferences below. Finally, I have used agglomerative clustering with 2 and 4 clusters to see if I am succesfully able to group sportsmen and academicians and when n=4 if I am able to group all 5 different proffesions in 4 seperate clusters. The inference for this can also be found towards the end of the notebook.
### The conclusion/inferences of the results can be found towards the end of the notebook

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Normalize functions
# 2 different types of normalizations 
def l1_normalize(v):
    norm = np.sum(np.abs(v))
    return v / norm

def l2_normalize(v):
    norm = np.sqrt(np.sum(np.square(v)))
    return v / norm

In [3]:
# For calculating the Euclidean Distance

def euclidean_distance(x,y,normalize=False):
    if normalize==True:
        x=l2_normalize(x)
        y=l2_normalize(y)
    return np.sqrt(np.sum((x-y)**2))

In [4]:
# For calculating the Cosine Similarity

def cosine_similarity(x, y):
    return np.dot(x, y) / (np.sqrt(np.dot(x, x)) * np.sqrt(np.dot(y, y)))

In [5]:
# For testing 
x1=np.array([10,10])
x2=np.array([20,20])
x3=np.array([1000,1000])

In [6]:
euclidean_distance(x1,x2,normalize = True)

0.0

In [7]:
cosine_similarity(x1,x2)

0.9999999999999999

### pip install Wikipedia

In [8]:
import wikipedia

In [9]:
# The first five names are of soccer players
# Second five are of basketball players
# Third five are of indian statisticians 
# Last five are of indian scientists/physicians

In [10]:
TwentyNames = ['Lionel_Messi','Cristiano_Ronaldo','Neymar','Luis_Suárez','Eden_Hazard',
               'LeBron_James','Michael_Jordan','Kevin_Durant','Kobe_Bryant','Stephen_Curry',
               'Prasanta_Chandra_Mahalanobis','C._R._Rao','Raj_Chandra_Bose','Jayanta_Kumar_Ghosh','Arup_Bose',
               'C._V._Raman','A._P._J._Abdul_Kalam','Vikram_Sarabhai','Srinivasa_Ramanujan','Satyendra_Nath_Bose'
              ]

In [11]:
article = []

for i in TwentyNames:
    article.append(wikipedia.page(i).content)

In [12]:
#importing Count vectorizer to create a token array of counts of words(frequency) in each text document
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
#creating count vectorizers and accessing all the pages and getting frequencies
cv=CountVectorizer()
Cv_array = cv.fit_transform(article).toarray()

In [14]:
#creating a celebrity list
people_euc = pd.DataFrame(TwentyNames,columns = ['Famous People'])
#people_euc

In [15]:
people_euc_norm =  people_euc.copy()
people_cosine = people_euc.copy()

In [16]:
# both functions take 2 names from the TwentyNames, returns the euclidian dist and cosine similarity
def dist1(a,b,normalize=False):
    x = Cv_array[TwentyNames.index(a)]
    y = Cv_array[TwentyNames.index(b)]
    return euclidean_distance(x,y,normalize)

def dist2(a,b):
    x = Cv_array[TwentyNames.index(a)]
    y = Cv_array[TwentyNames.index(b)]
    return cosine_similarity(x,y)

In [17]:
# without normalization
for i in TwentyNames:
    people_euc[i] = people_euc['Famous People'].apply(lambda x : dist1(x,i))
    
# with normalization
for i in TwentyNames:
    people_euc_norm[i] = people_euc_norm['Famous People'].apply(lambda x : dist1(x,i,True))
    
# cosine similarity 
for i in TwentyNames:
    people_cosine[i] = people_cosine['Famous People'].apply(lambda x : dist2(x,i))

In [18]:
people_euc.set_index('Famous People', inplace = True) 
people_euc_norm.set_index('Famous People', inplace = True) 
people_cosine.set_index('Famous People', inplace = True)

In [19]:
people_euc.head()

,Lionel_Messi,Cristiano_Ronaldo,Neymar,Luis_Suárez,Eden_Hazard,LeBron_James,Michael_Jordan,Kevin_Durant,Kobe_Bryant,Stephen_Curry,Prasanta_Chandra_Mahalanobis,C._R._Rao,Raj_Chandra_Bose,Jayanta_Kumar_Ghosh,Arup_Bose,C._V._Raman,A._P._J._Abdul_Kalam,Vikram_Sarabhai,Srinivasa_Ramanujan,Satyendra_Nath_Bose
Famous People,,,,,,,,,,,,,,,,,,,,
Lionel_Messi,0.000000,615.397433,1090.321512,1067.356548,925.216731,1054.549193,1085.531667,1390.865558,884.128950,1038.073697,1631.576538,1728.462901,1734.938039,1787.641463,1790.258361,1571.853365,1355.083392,1756.404851,1347.125458,1613.747192
Cristiano_Ronaldo,615.397433,0.000000,746.326336,725.053102,613.087269,732.136599,767.589083,1017.553438,686.642556,731.381569,1251.763556,1347.392296,1354.056867,1406.722432,1409.364751,1194.379755,992.272644,1375.947673,991.907758,1234.546070
Neymar,1090.321512,746.326336,0.000000,402.138036,505.188084,491.396988,516.608169,489.701950,756.649853,533.126627,681.930348,769.518681,775.905278,825.410807,827.956521,633.807542,510.967709,795.817190,540.562670,667.963322
Luis_Suárez,1067.356548,725.053102,402.138036,0.000000,499.984000,499.643873,524.862839,516.864586,750.597096,540.461840,710.927563,797.465987,804.182815,853.340495,856.030957,663.235252,530.922782,824.777546,557.213604,696.328945
Eden_Hazard,925.216731,613.087269,505.188084,499.984000,0.000000,545.776511,566.892406,698.610764,669.956715,558.849711,914.220980,1006.799881,1012.278618,1063.023988,1065.475011,861.597934,701.583210,1032.117241,723.815584,901.676217

In [20]:
people_euc_norm.head()

,Lionel_Messi,Cristiano_Ronaldo,Neymar,Luis_Suárez,Eden_Hazard,LeBron_James,Michael_Jordan,Kevin_Durant,Kobe_Bryant,Stephen_Curry,Prasanta_Chandra_Mahalanobis,C._R._Rao,Raj_Chandra_Bose,Jayanta_Kumar_Ghosh,Arup_Bose,C._V._Raman,A._P._J._Abdul_Kalam,Vikram_Sarabhai,Srinivasa_Ramanujan,Satyendra_Nath_Bose
Famous People,,,,,,,,,,,,,,,,,,,,
Lionel_Messi,0.000000,0.300481,0.412189,0.408687,0.409295,0.473257,0.506251,0.463605,0.480171,0.496594,0.553848,0.694686,0.697867,0.960623,0.898342,0.614520,0.576723,0.633655,0.630954,0.611221
Cristiano_Ronaldo,0.300481,0.000000,0.423460,0.417394,0.406664,0.479299,0.514846,0.465545,0.491727,0.502189,0.550384,0.683377,0.689009,0.950254,0.886580,0.613703,0.580914,0.633394,0.635879,0.607504
Neymar,0.412189,0.423460,0.000000,0.465566,0.464933,0.529738,0.562723,0.519679,0.539855,0.540600,0.603816,0.723555,0.731634,0.975649,0.922129,0.649559,0.625543,0.678432,0.677881,0.650101
Luis_Suárez,0.408687,0.417394,0.465566,0.000000,0.465803,0.536605,0.568256,0.525454,0.545236,0.549349,0.611034,0.721185,0.732902,0.968207,0.916262,0.658487,0.624212,0.692750,0.675156,0.654057
Eden_Hazard,0.409295,0.406664,0.464933,0.465803,0.000000,0.520463,0.542124,0.502685,0.514225,0.527127,0.589250,0.730922,0.726715,0.982580,0.926093,0.642263,0.625021,0.659429,0.689139,0.654932

In [21]:
people_cosine.head()

,Lionel_Messi,Cristiano_Ronaldo,Neymar,Luis_Suárez,Eden_Hazard,LeBron_James,Michael_Jordan,Kevin_Durant,Kobe_Bryant,Stephen_Curry,Prasanta_Chandra_Mahalanobis,C._R._Rao,Raj_Chandra_Bose,Jayanta_Kumar_Ghosh,Arup_Bose,C._V._Raman,A._P._J._Abdul_Kalam,Vikram_Sarabhai,Srinivasa_Ramanujan,Satyendra_Nath_Bose
Famous People,,,,,,,,,,,,,,,,,,,,
Lionel_Messi,1.000000,0.954856,0.915050,0.916487,0.916239,0.888014,0.871855,0.892535,0.884718,0.876697,0.846626,0.758706,0.756491,0.538602,0.596491,0.811183,0.833695,0.799240,0.800949,0.813204
Cristiano_Ronaldo,0.954856,1.000000,0.910341,0.912891,0.917312,0.885136,0.867467,0.891634,0.879102,0.873903,0.848539,0.766498,0.762633,0.548509,0.606988,0.811685,0.831269,0.799406,0.797829,0.815469
Neymar,0.915050,0.910341,1.000000,0.891624,0.891919,0.859689,0.841671,0.864967,0.854278,0.853876,0.817703,0.738234,0.732356,0.524054,0.574839,0.789037,0.804348,0.769865,0.770238,0.788684
Luis_Suárez,0.916487,0.912891,0.891624,1.000000,0.891514,0.856028,0.838543,0.861949,0.851359,0.849108,0.813319,0.739946,0.731428,0.531288,0.580232,0.783198,0.805180,0.760049,0.772082,0.786105
Eden_Hazard,0.916239,0.917312,0.891919,0.891514,1.000000,0.864559,0.853051,0.873654,0.867786,0.861069,0.826392,0.732877,0.735942,0.517268,0.571176,0.793749,0.804674,0.782577,0.762544,0.785532

In [22]:
def knn_euclidean(Col,k=3,normalize=False):
    indx= []
    col1 = []
    if (normalize==True):
        indx = people_euc_norm.loc[people_euc_norm.index != Col,Col]
    else:
        indx = people_euc.loc[people_euc.index != Col,Col]
    for i in indx.index:
        col1.append([indx[i],i])   
    col1.sort()
    vals = []
    for i in range(k):
        vals.append(col1[i][1])
    return vals

In [23]:
def knn_cosine(Col,k=3):
    col1 = []
    indx = people_cosine.loc[people_cosine.index != Col,Col]
    for i in indx.index:
        col1.append([indx[i],i])   
    col1.sort(reverse=True)  
    vals = []
    for i in range(k):
        vals.append(col1[i][1])   
    return vals

In [24]:
three_nearest = pd.DataFrame(TwentyNames,columns = ['Famous'])
three_nearest.head()

              Famous
0       Lionel_Messi
1  Cristiano_Ronaldo
2             Neymar
3        Luis_Suárez
4        Eden_Hazard

In [25]:
three_nearest['3NN_euclidean_withiout normalization'] = three_nearest['Famous'].apply(lambda x : knn_euclidean(x,3))
three_nearest['3NN_euclidean_with normalization'] = three_nearest['Famous'].apply(lambda x : knn_euclidean(x,3,True))
three_nearest['3NN_cosine similarity'] = three_nearest['Famous'].apply(lambda x : knn_cosine(x,3))

In [26]:
three_nearest

,Famous,3NN_euclidean_withiout normalization,3NN_euclidean_with normalization,3NN_cosine similarity
0,Lionel_Messi,"[Cristiano_Ronaldo, Kobe_Bryant, Eden_Hazard]","[Cristiano_Ronaldo, Luis_Suárez, Eden_Hazard]","[Cristiano_Ronaldo, Luis_Suárez, Eden_Hazard]"
1,Cristiano_Ronaldo,"[Eden_Hazard, Lionel_Messi, Kobe_Bryant]","[Lionel_Messi, Eden_Hazard, Luis_Suárez]","[Lionel_Messi, Eden_Hazard, Luis_Suárez]"
2,Neymar,"[Luis_Suárez, Kevin_Durant, LeBron_James]","[Lionel_Messi, Cristiano_Ronaldo, Eden_Hazard]","[Lionel_Messi, Cristiano_Ronaldo, Eden_Hazard]"
3,Luis_Suárez,"[Neymar, LeBron_James, Eden_Hazard]","[Lionel_Messi, Cristiano_Ronaldo, Neymar]","[Lionel_Messi, Cristiano_Ronaldo, Neymar]"
4,Eden_Hazard,"[Luis_Suárez, Neymar, LeBron_James]","[Cristiano_Ronaldo, Lionel_Messi, Neymar]","[Cristiano_Ronaldo, Lionel_Messi, Neymar]"
5,LeBron_James,"[Michael_Jordan, Stephen_Curry, Neymar]","[Kevin_Durant, Kobe_Bryant, Stephen_Curry]","[Kevin_Durant, Kobe_Bryant, Stephen_Curry]"
6,Michael_Jordan,"[LeBron_James, Stephen_Curry, Neymar]","[LeBron_James, Kevin_Durant, Kobe_Bryant]","[LeBron_James, Kevin_Durant, Kobe_Bryant]"
7,Kevin_Durant,"[C._V._Raman, Satyendra_Nath_Bose, Prasanta_Ch...","[LeBron_James, Stephen_Curry, Kobe_Bryant]","[LeBron_James, Stephen_Curry, Kobe_Bryant]"
8,Kobe_Bryant,"[Stephen_Curry, LeBron_James, Michael_Jordan]","[Kevin_Durant, LeBron_James, Stephen_Curry]","[Kevin_Durant, LeBron_James, Stephen_Curry]"
9,Stephen_Curry,"[LeBron_James, Michael_Jordan, Neymar]","[Kevin_Durant, LeBron_James, Kobe_Bryant]","[Kevin_Durant, LeBron_James, Kobe_Bryant]"
10,Prasanta_Chandra_Mahalanobis,"[Satyendra_Nath_Bose, C._R._Rao, Raj_Chandra_B...","[A._P._J._Abdul_Kalam, Satyendra_Nath_Bose, Ra...","[A._P._J._Abdul_Kalam, Satyendra_Nath_Bose, Ra..."
11,C._R._Rao,"[Raj_Chandra_Bose, Vikram_Sarabhai, Jayanta_Ku...","[Prasanta_Chandra_Mahalanobis, A._P._J._Abdul_...","[Prasanta_Chandra_Mahalanobis, A._P._J._Abdul_..."
12,Raj_Chandra_Bose,"[C._R._Rao, Vikram_Sarabhai, Jayanta_Kumar_Ghosh]","[Satyendra_Nath_Bose, Prasanta_Chandra_Mahalan...","[Satyendra_Nath_Bose, Prasanta_Chandra_Mahalan..."
13,Jayanta_Kumar_Ghosh,"[Arup_Bose, Vikram_Sarabhai, Raj_Chandra_Bose]","[Arup_Bose, C._R._Rao, Prasanta_Chandra_Mahala...","[Arup_Bose, C._R._Rao, Prasanta_Chandra_Mahala..."
14,Arup_Bose,"[Jayanta_Kumar_Ghosh, Vikram_Sarabhai, Raj_Cha...","[Jayanta_Kumar_Ghosh, C._R._Rao, Prasanta_Chan...","[Jayanta_Kumar_Ghosh, C._R._Rao, Prasanta_Chan..."
15,C._V._Raman,"[Prasanta_Chandra_Mahalanobis, Satyendra_Nath_...","[Prasanta_Chandra_Mahalanobis, Satyendra_Nath_...","[Prasanta_Chandra_Mahalanobis, Satyendra_Nath_..."
16,A._P._J._Abdul_Kalam,"[Kevin_Durant, Srinivasa_Ramanujan, C._V._Raman]","[Prasanta_Chandra_Mahalanobis, Satyendra_Nath_...","[Prasanta_Chandra_Mahalanobis, Satyendra_Nath_..."
17,Vikram_Sarabhai,"[Arup_Bose, Jayanta_Kumar_Ghosh, Raj_Chandra_B...","[Prasanta_Chandra_Mahalanobis, A._P._J._Abdul_...","[Prasanta_Chandra_Mahalanobis, A._P._J._Abdul_..."
18,Srinivasa_Ramanujan,"[A._P._J._Abdul_Kalam, Kevin_Durant, C._V._Raman]","[Prasanta_Chandra_Mahalanobis, A._P._J._Abdul_...","[Prasanta_Chandra_Mahalanobis, A._P._J._Abdul_..."
19,Satyendra_Nath_Bose,"[Prasanta_Chandra_Mahalanobis, Raj_Chandra_Bos...","[Raj_Chandra_Bose, Prasanta_Chandra_Mahalanobi...","[Raj_Chandra_Bose, Prasanta_Chandra_Mahalanobi..."

## Conclusions 

### If we look at the second column which is euclidean distance without normalization, we see a lot of groupings have been done incorrectly for example looking at the first row we have [Cristiano_Ronaldo, Kobe_Bryant, Eden_Hazard] grouped similar to Messi. Two out of the 3 are soccer players but Kobe Bryant has been grouped wrongly over here. Possible reasons are that since we are using euclidean distance, we are only concerned with the magnitutde and not the behavioural similarity. Maybe articles on Kobe Bryant and Messi have the same length that's why they have been grouped together.

In [27]:
Eden = wikipedia.page('Eden_Hazard').content
len(Eden)

60121

In [28]:
Messi = wikipedia.page('Lionel_Messi').content
len(Messi)

110853

In [29]:
Kobe = wikipedia.page('Kobe_Bryant').content
len(Kobe)

71827

In [30]:
Ronaldo = wikipedia.page('Cristiano_Ronaldo').content
len(Ronaldo)

86736

### All 4 have similar magnitutde and hence have been grouped togther even though Kobe is a basketball player and the other 3 are soccer players

### Still looking at the first row if we look at the third column which is euclidean KNN with normalization and if we look at the fourth column which is cosine similarity, we notice a difference in the groupings which is that the wrongly grouped basketball player Kobe is no longer there and we notice Suarez in his place. The output is [Cristiano_Ronaldo, Luis_Suárez, Eden_Hazard]. The reason for this correction is that now we are no longer interested in the magnitude of the vectors/articles, instead we are interested in the behavorial similarity between the famous people and as we from the result all the soccer players have been grouped together. 

### Similar patterns can be seen in all the rows and the reason for that has been explained above.

In [31]:
from sklearn.cluster import AgglomerativeClustering

In [32]:
# Here we are clustering in 2 clusters using cosine similarity 
# and expect to get 2 clusters, 1 with all sportsmen and the other with all academicians
cluster_n2_cos = AgglomerativeClustering(n_clusters=2).fit(people_cosine)
pred1 = cluster_n2_cos.labels_.tolist()
pred1

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0]

In [33]:
# Here we are clustering in 2 clusters using euclidean distance with normalization 
# and expect to get 2 clusters, 1 with all sportsmen and the other with all academicians
cluster_n2_norm = AgglomerativeClustering(n_clusters=2).fit(people_euc_norm)
pred2 = cluster_n2_norm.labels_.tolist()
pred2

/Users/akcterp/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py:482: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  return linkage(y, method='ward', metric='euclidean')

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [34]:
# Here we are clustering in 2 clusters using euclidean distance without normalization on actual data
# and expect to get 2 clusters, 1 with all sportsmen and the other with all academicians
cluster_n2_act = AgglomerativeClustering(n_clusters=2).fit(people_euc)
pred3 = cluster_n2_act.labels_.tolist()
pred3

/Users/akcterp/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py:482: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  return linkage(y, method='ward', metric='euclidean')

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1]

In [35]:
# Here we are clustering in 4 clusters using cosine similarity 
# and expect to get 4 clusters, each cluster with 5 people ideally, 5 soccer players, 5 basketball players, 
# 5 statisticians and lastly 5 scientists 
cluster_n4_cos = AgglomerativeClustering(n_clusters=4).fit(people_cosine)
pred4 = cluster_n4_cos.labels_.tolist()
pred4

[2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0]

In [36]:
# Here we are clustering in 4 clusters using euclidean distance with normalization 
# and expect to get 4 clusters, each cluster with 5 people ideally, 5 soccer players, 5 basketball players, 
# 5 statisticians and lastly 5 scientists
cluster_n4_norm = AgglomerativeClustering(n_clusters=4).fit(people_euc_norm)
pred5 = cluster_n4_norm.labels_.tolist()
pred5

/Users/akcterp/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py:482: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  return linkage(y, method='ward', metric='euclidean')

[1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0]

In [37]:
# Here we are clustering in 4 clusters using euclidean distance without normalization on the actual data 
# and expect to get 4 clusters, each cluster with 5 people ideally, 5 soccer players, 5 basketball players, 
# 5 statisticians and lastly 5 scientists
cluster_n4_act = AgglomerativeClustering(n_clusters=4).fit(people_euc)
pred6 = cluster_n4_act.labels_.tolist()
pred6

/Users/akcterp/anaconda3/lib/python3.7/site-packages/scipy/cluster/hierarchy.py:482: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  return linkage(y, method='ward', metric='euclidean')

[0, 0, 2, 2, 2, 2, 2, 3, 0, 2, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1]

## Conclusions

### For a better understanding, we can add another column to our data frame of predicted classes or we can make inferences directly from the list outputs above

### I will be adding 2 columns of predicted classes to all 3 dataframes

In [38]:
# adding pred columns to euclidean distance without normalization on actual data for 2 and 4 clusters
people_euc['pred_2clusters'] = pred3
people_euc['pred_4clusters'] = pred6
people_euc

,Lionel_Messi,Cristiano_Ronaldo,Neymar,Luis_Suárez,Eden_Hazard,LeBron_James,Michael_Jordan,Kevin_Durant,Kobe_Bryant,Stephen_Curry,...,Raj_Chandra_Bose,Jayanta_Kumar_Ghosh,Arup_Bose,C._V._Raman,A._P._J._Abdul_Kalam,Vikram_Sarabhai,Srinivasa_Ramanujan,Satyendra_Nath_Bose,pred_2clusters,pred_4clusters
Famous People,,,,,,,,,,,,,,,,,,,,,
Lionel_Messi,0.000000,615.397433,1090.321512,1067.356548,925.216731,1054.549193,1085.531667,1390.865558,884.128950,1038.073697,...,1734.938039,1787.641463,1790.258361,1571.853365,1355.083392,1756.404851,1347.125458,1613.747192,0,0
Cristiano_Ronaldo,615.397433,0.000000,746.326336,725.053102,613.087269,732.136599,767.589083,1017.553438,686.642556,731.381569,...,1354.056867,1406.722432,1409.364751,1194.379755,992.272644,1375.947673,991.907758,1234.546070,0,0
Neymar,1090.321512,746.326336,0.000000,402.138036,505.188084,491.396988,516.608169,489.701950,756.649853,533.126627,...,775.905278,825.410807,827.956521,633.807542,510.967709,795.817190,540.562670,667.963322,0,2
Luis_Suárez,1067.356548,725.053102,402.138036,0.000000,499.984000,499.643873,524.862839,516.864586,750.597096,540.461840,...,804.182815,853.340495,856.030957,663.235252,530.922782,824.777546,557.213604,696.328945,0,2
Eden_Hazard,925.216731,613.087269,505.188084,499.984000,0.000000,545.776511,566.892406,698.610764,669.956715,558.849711,...,1012.278618,1063.023988,1065.475011,861.597934,701.583210,1032.117241,723.815584,901.676217,0,2
LeBron_James,1054.549193,732.136599,491.396988,499.643873,545.776511,0.000000,411.367233,531.448022,603.912245,424.022405,...,885.937921,936.846839,940.161156,732.974079,559.166344,907.559364,585.806282,768.417855,0,2
Michael_Jordan,1085.531667,767.589083,516.608169,524.862839,566.892406,411.367233,0.000000,552.038042,632.271303,472.863617,...,877.895780,929.018299,932.698236,727.694991,562.867658,899.432599,595.434295,764.476945,0,2
Kevin_Durant,1390.865558,1017.553438,489.701950,516.864586,698.610764,531.448022,552.038042,0.000000,908.672108,596.031878,...,418.773208,467.291130,470.382823,301.642172,334.077835,437.854999,406.110822,323.606242,0,3
Kobe_Bryant,884.128950,686.642556,756.649853,750.597096,669.956715,603.912245,632.271303,908.672108,0.000000,600.347399,...,1265.962085,1316.627510,1319.795818,1108.980162,913.744494,1286.038102,925.151339,1149.492932,0,0
Stephen_Curry,1038.073697,731.381569,533.126627,540.461840,558.849711,424.022405,472.863617,596.031878,600.347399,0.000000,...,951.062038,1000.592325,1003.603507,803.323098,649.133268,971.011328,669.891036,840.508774,0,2
Prasanta_Chandra_Mahalanobis,1631.576538,1251.763556,681.930348,710.927563,914.220980,785.125468,778.532594,327.858201,1165.006438,854.417345,...,136.403812,186.901043,191.815015,162.151164,415.447951,160.499221,484.029958,116.644760,1,1
C._R._Rao,1728.462901,1347.392296,769.518681,797.465987,1006.799881,877.989749,871.437318,411.891976,1259.235482,944.143527,...,63.921827,82.522724,86.296002,229.148424,507.347021,70.370448,568.310654,171.224998,1,1
Raj_Chandra_Bose,1734.938039,1354.056867,775.905278,804.182815,1012.278618,885.937921,877.895780,418.773208,1265.962085,951.062038,...,0.000000,76.941536,79.479557,234.770100,516.492982,64.575537,575.377268,164.893905,1,1
Jayanta_Kumar_Ghosh,1787.641463,1406.722432,825.410807,853.340495,1063.023988,936.846839,929.018299,467.291130,1316.627510,1000.592325,...,76.941536,0.000000,27.367864,281.817317,567.199260,51.730069,625.580530,223.830293,1,1
Arup_Bose,1790.258361,1409.364751,827.956521,856.030957,1065.475011,940.161156,932.698236,470.382823,1319.795818,1003.603507,...,79.479557,27.367864,0.000000,285.317367,572.062934,51.623638,628.671615,226.143760,1,1
C._V._Raman,1571.853365,1194.379755,633.807542,663.235252,861.597934,732.974079,727.694991,301.642172,1108.980162,803.323098,...,234.770100,281.817317,285.317367,0.000000,380.497043,254.890172,450.748267,169.224703,1,1
A._P._J._Abdul_Kalam,1355.083392,992.272644,510.967709,530.922782,701.583210,559.166344,562.867658,334.077835,913.744494,649.133268,...,516.492982,567.199260,572.062934,380.497043,0.000000,539.876838,363.403357,406.119441,0,3
Vikram_Sarabhai,1756.404851,1375.947673,795.817190,824.777546,1032.117241,907.559364,899.432599,437.854999,1286.038102,971.011328,...,64.575537,51.730069,51.623638,254.890172,539.876838,0.000000,601.136424,199.459269,1,1
Srinivasa_Ramanujan,1347.125458,991.907758,540.562670,557.213604,723.815584,585.806282,595.434295,406.110822,925.151339,669.891036,...,575.377268,625.580530,628.671615,450.748267,363.403357,601.136424,0.000000,466.560821,0,3
Satyendra_Nath_Bose,1613.747192,1234.546070,667.963322,696.328945,901.676217,768.417855,764.476945,323.606242,1149.492932,840.508774,...,164.893905,223.830293,226.143760,169.224703,406.119441,199.459269,466.560821,0.000000,1,1

In [39]:
# adding pred columns to euclidean distance with normalization for 2 and 4 clusters
people_euc_norm['pred_2clusters'] = pred2
people_euc_norm['pred_4clusters'] = pred5
people_euc_norm

,Lionel_Messi,Cristiano_Ronaldo,Neymar,Luis_Suárez,Eden_Hazard,LeBron_James,Michael_Jordan,Kevin_Durant,Kobe_Bryant,Stephen_Curry,...,Raj_Chandra_Bose,Jayanta_Kumar_Ghosh,Arup_Bose,C._V._Raman,A._P._J._Abdul_Kalam,Vikram_Sarabhai,Srinivasa_Ramanujan,Satyendra_Nath_Bose,pred_2clusters,pred_4clusters
Famous People,,,,,,,,,,,,,,,,,,,,,
Lionel_Messi,0.000000,0.300481,0.412189,0.408687,0.409295,0.473257,0.506251,0.463605,0.480171,0.496594,...,0.697867,0.960623,0.898342,0.614520,0.576723,0.633655,0.630954,0.611221,1,1
Cristiano_Ronaldo,0.300481,0.000000,0.423460,0.417394,0.406664,0.479299,0.514846,0.465545,0.491727,0.502189,...,0.689009,0.950254,0.886580,0.613703,0.580914,0.633394,0.635879,0.607504,1,1
Neymar,0.412189,0.423460,0.000000,0.465566,0.464933,0.529738,0.562723,0.519679,0.539855,0.540600,...,0.731634,0.975649,0.922129,0.649559,0.625543,0.678432,0.677881,0.650101,1,1
Luis_Suárez,0.408687,0.417394,0.465566,0.000000,0.465803,0.536605,0.568256,0.525454,0.545236,0.549349,...,0.732902,0.968207,0.916262,0.658487,0.624212,0.692750,0.675156,0.654057,1,1
Eden_Hazard,0.409295,0.406664,0.464933,0.465803,0.000000,0.520463,0.542124,0.502685,0.514225,0.527127,...,0.726715,0.982580,0.926093,0.642263,0.625021,0.659429,0.689139,0.654932,1,1
LeBron_James,0.473257,0.479299,0.529738,0.536605,0.520463,0.000000,0.429760,0.359668,0.415041,0.423019,...,0.693021,0.930566,0.884708,0.610220,0.559187,0.645649,0.628356,0.596507,1,3
Michael_Jordan,0.506251,0.514846,0.562723,0.568256,0.542124,0.429760,0.000000,0.440832,0.443108,0.473600,...,0.693320,0.936586,0.904120,0.620543,0.577040,0.644641,0.651531,0.617571,1,3
Kevin_Durant,0.463605,0.465545,0.519679,0.525454,0.502685,0.359668,0.440832,0.000000,0.400418,0.377688,...,0.700388,0.938273,0.897118,0.617440,0.586989,0.642437,0.660149,0.619555,1,3
Kobe_Bryant,0.480171,0.491727,0.539855,0.545236,0.514225,0.415041,0.443108,0.400418,0.000000,0.436015,...,0.727114,0.973547,0.934216,0.633570,0.594273,0.658789,0.662167,0.637132,1,3
Stephen_Curry,0.496594,0.502189,0.540600,0.549349,0.527127,0.423019,0.473600,0.377688,0.436015,0.000000,...,0.734652,0.972003,0.929502,0.650715,0.625637,0.676873,0.682577,0.654177,1,3
Prasanta_Chandra_Mahalanobis,0.553848,0.550384,0.603816,0.611034,0.589250,0.546909,0.556527,0.553175,0.578505,0.599680,...,0.498201,0.731999,0.707687,0.520574,0.475793,0.511738,0.568738,0.478937,0,0
C._R._Rao,0.694686,0.683377,0.723555,0.721185,0.730922,0.669663,0.688022,0.684157,0.717746,0.721353,...,0.595781,0.696166,0.666824,0.636643,0.584386,0.648188,0.656073,0.592607,0,0
Raj_Chandra_Bose,0.697867,0.689009,0.731634,0.732902,0.726715,0.693021,0.693320,0.700388,0.727114,0.734652,...,0.000000,0.750999,0.711363,0.642700,0.622039,0.659623,0.669538,0.448728,0,0
Jayanta_Kumar_Ghosh,0.960623,0.950254,0.975649,0.968207,0.982580,0.930566,0.936586,0.938273,0.973547,0.972003,...,0.750999,0.000000,0.659335,0.859939,0.822109,0.824560,0.893178,0.819528,0,2
Arup_Bose,0.898342,0.886580,0.922129,0.916262,0.926093,0.884708,0.904120,0.897118,0.934216,0.929502,...,0.711363,0.659335,0.000000,0.817360,0.798723,0.794572,0.832071,0.729407,0,2
C._V._Raman,0.614520,0.613703,0.649559,0.658487,0.642263,0.610220,0.620543,0.617440,0.633570,0.650715,...,0.642700,0.859939,0.817360,0.000000,0.581506,0.616104,0.652186,0.574234,0,0
A._P._J._Abdul_Kalam,0.576723,0.580914,0.625543,0.624212,0.625021,0.559187,0.577040,0.586989,0.594273,0.625637,...,0.622039,0.822109,0.798723,0.581506,0.000000,0.589787,0.576836,0.555784,0,0
Vikram_Sarabhai,0.633655,0.633394,0.678432,0.692750,0.659429,0.645649,0.644641,0.642437,0.658789,0.676873,...,0.659623,0.824560,0.794572,0.616104,0.589787,0.000000,0.707472,0.625323,0,0
Srinivasa_Ramanujan,0.630954,0.635879,0.677881,0.675156,0.689139,0.628356,0.651531,0.660149,0.662167,0.682577,...,0.669538,0.893178,0.832071,0.652186,0.576836,0.707472,0.000000,0.592879,0,0
Satyendra_Nath_Bose,0.611221,0.607504,0.650101,0.654057,0.654932,0.596507,0.617571,0.619555,0.637132,0.654177,...,0.448728,0.819528,0.729407,0.574234,0.555784,0.625323,0.592879,0.000000,0,0

In [40]:
# adding pred columns to cosine similarity for 2 and 4 clusters
people_cosine['pred_2clusters'] = pred1
people_cosine['pred_4clusters'] = pred4
people_cosine

,Lionel_Messi,Cristiano_Ronaldo,Neymar,Luis_Suárez,Eden_Hazard,LeBron_James,Michael_Jordan,Kevin_Durant,Kobe_Bryant,Stephen_Curry,...,Raj_Chandra_Bose,Jayanta_Kumar_Ghosh,Arup_Bose,C._V._Raman,A._P._J._Abdul_Kalam,Vikram_Sarabhai,Srinivasa_Ramanujan,Satyendra_Nath_Bose,pred_2clusters,pred_4clusters
Famous People,,,,,,,,,,,,,,,,,,,,,
Lionel_Messi,1.000000,0.954856,0.915050,0.916487,0.916239,0.888014,0.871855,0.892535,0.884718,0.876697,...,0.756491,0.538602,0.596491,0.811183,0.833695,0.799240,0.800949,0.813204,0,2
Cristiano_Ronaldo,0.954856,1.000000,0.910341,0.912891,0.917312,0.885136,0.867467,0.891634,0.879102,0.873903,...,0.762633,0.548509,0.606988,0.811685,0.831269,0.799406,0.797829,0.815469,0,2
Neymar,0.915050,0.910341,1.000000,0.891624,0.891919,0.859689,0.841671,0.864967,0.854278,0.853876,...,0.732356,0.524054,0.574839,0.789037,0.804348,0.769865,0.770238,0.788684,0,2
Luis_Suárez,0.916487,0.912891,0.891624,1.000000,0.891514,0.856028,0.838543,0.861949,0.851359,0.849108,...,0.731428,0.531288,0.580232,0.783198,0.805180,0.760049,0.772082,0.786105,0,2
Eden_Hazard,0.916239,0.917312,0.891919,0.891514,1.000000,0.864559,0.853051,0.873654,0.867786,0.861069,...,0.735942,0.517268,0.571176,0.793749,0.804674,0.782577,0.762544,0.785532,0,2
LeBron_James,0.888014,0.885136,0.859689,0.856028,0.864559,1.000000,0.907653,0.935320,0.913871,0.910527,...,0.759861,0.567024,0.608646,0.813816,0.843655,0.791568,0.802584,0.822090,0,3
Michael_Jordan,0.871855,0.867467,0.841671,0.838543,0.853051,0.907653,1.000000,0.902833,0.901827,0.887852,...,0.759654,0.561404,0.591284,0.807463,0.833512,0.792219,0.787753,0.809303,0,3
Kevin_Durant,0.892535,0.891634,0.864967,0.861949,0.873654,0.935320,0.902833,1.000000,0.919833,0.928676,...,0.754728,0.559822,0.597590,0.809384,0.827722,0.793637,0.782102,0.808076,0,3
Kobe_Bryant,0.884718,0.879102,0.854278,0.851359,0.867786,0.913871,0.901827,0.919833,1.000000,0.904946,...,0.735653,0.526104,0.563621,0.799294,0.823420,0.782999,0.780767,0.797031,0,3
Stephen_Curry,0.876697,0.873903,0.853876,0.849108,0.861069,0.910527,0.887852,0.928676,0.904946,1.000000,...,0.730143,0.527605,0.568013,0.788285,0.804289,0.770922,0.767045,0.786026,0,3
Prasanta_Chandra_Mahalanobis,0.846626,0.848539,0.817703,0.813319,0.826392,0.850445,0.845139,0.846999,0.832666,0.820192,...,0.875898,0.732089,0.749590,0.864501,0.886811,0.869062,0.838268,0.885310,0,0
C._R._Rao,0.758706,0.766498,0.738234,0.739946,0.732877,0.775775,0.763313,0.765965,0.742420,0.739825,...,0.822523,0.757676,0.777673,0.797343,0.829246,0.789926,0.784784,0.824408,0,0
Raj_Chandra_Bose,0.756491,0.762633,0.732356,0.731428,0.735942,0.759861,0.759654,0.754728,0.735653,0.730143,...,1.000000,0.718000,0.746981,0.793468,0.806534,0.782449,0.775859,0.899322,0,0
Jayanta_Kumar_Ghosh,0.538602,0.548509,0.524054,0.531288,0.517268,0.567024,0.561404,0.559822,0.526104,0.527605,...,0.718000,1.000000,0.782638,0.630252,0.662068,0.660050,0.601117,0.664187,1,1
Arup_Bose,0.596491,0.606988,0.574839,0.580232,0.571176,0.608646,0.591284,0.597590,0.563621,0.568013,...,0.746981,0.782638,1.000000,0.665962,0.681020,0.684328,0.653829,0.733983,1,1
C._V._Raman,0.811183,0.811685,0.789037,0.783198,0.793749,0.813816,0.807463,0.809384,0.799294,0.788285,...,0.793468,0.630252,0.665962,1.000000,0.830925,0.810208,0.787327,0.835127,0,0
A._P._J._Abdul_Kalam,0.833695,0.831269,0.804348,0.805180,0.804674,0.843655,0.833512,0.827722,0.823420,0.804289,...,0.806534,0.662068,0.681020,0.830925,1.000000,0.826075,0.833630,0.845552,0,0
Vikram_Sarabhai,0.799240,0.799406,0.769865,0.760049,0.782577,0.791568,0.792219,0.793637,0.782999,0.770922,...,0.782449,0.660050,0.684328,0.810208,0.826075,1.000000,0.749742,0.804486,0,0
Srinivasa_Ramanujan,0.800949,0.797829,0.770238,0.772082,0.762544,0.802584,0.787753,0.782102,0.780767,0.767045,...,0.775859,0.601117,0.653829,0.787327,0.833630,0.749742,1.000000,0.824247,0,0
Satyendra_Nath_Bose,0.813204,0.815469,0.788684,0.786105,0.785532,0.822090,0.809303,0.808076,0.797031,0.786026,...,0.899322,0.664187,0.733983,0.835127,0.845552,0.804486,0.824247,1.000000,0,0

### Overall conclusion is that clustering in 2 clusters gives a better result than clustering in 4 clusters
### with 2 clusters the output is more accuarte since we have more margin of error 
### In a lot of cases, the output with even 2 clusters is not correct but that can be explained depending on wether we are using cosine similarity or euclidean distance or euclidean distance with normalization